version: '3'
services:
  wordpress:
    # depends_on:
    #   - db
    image: wordpress:latest
    restart: always
    volumes:
      - ./app:/var/www/html
    environment:
      WP_DB_HOST: ${WP_DB_HOST}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASSWORD: ${WP_DB_PASSWORD}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_ENV: ${WP_ENV}
      # WP_DB_HOST: checkoutafrica.cyi0rwnrx566.eu-west-2.rds.amazonaws.com
      # WP_DB_USER: checkoutafrica
      # WP_DB_PASSWORD: Striver1395
      # WP_DB_NAME: wordpress
      # WP_ENV: development
    ports:
      - 80:80
      - 443:443
    networks:
      - back
  # db: 
  #   image: mysql:5.7
  #   restart: always
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   networks:
  #     - back
  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: password
  #   networks:
  #     - back
networks:
  back:
volumes:
  db_data: